## Be Nice 

This should go without saying. We expect civility from reviewers and eBirders. Reviewing records is not simply a matter of quietly going through and reviewing records. Our strongest eBird reviewers take time to build relationships with our users and help to improve their birding skills and eBirding knowledge. You will become one of the primary points of contact between eBird and our user community. Please do what you can to encourage users in a supportive manner and help build the eBird community. People make mistakes. We encourage you to contact and assist them. If you continually treat records as Unconfirmed without letting people know, they are unlikely to learn, will keep making the same mistakes, and this will ultimately take more of your time. Be tactful when sharing information about an observer’s reputation, reporting history, or identification for a species record. We have very high expectations for reviewers to be professional and polite. Reviewers who do not treat users with respect will have their review privileges removed.  

We expect the same from eBirders—if you believe a user is not treating you professionally or with respect, please document the instance by saving those emails and send them to one of the eBird staff members. If we are not able to improve the situation, we may set that user’s data to personal-only (eBird Blocklist, see below). This is always a last resort and we have found that in almost all cases, we can remedy the situation in some other way. Threats of any kind from eBird users are not tolerated. If you receive a threat of any kind, notify eBird staff immediately. See the[ eBird Review Code of Conduct](https://support.ebird.org/support/solutions/articles/48000795278) for more detail. 

**Respectful Correspondence**

You will be corresponding with observers of all skill levels. Since skeptical inquiry about bird sightings can offend some people, please do your best to keep your inquiries respectful and tactful. Our automated emails are usually well-received and are a time-saver in the review process, but feel free to use all, some, or none of it in the email you send to eBirders. Often it is helpful to explain exactly why the species has raised questions. Quick Review has specific places to add this text and it is encouraged that you do so. 

It is not appropriate to contact people whose email addresses you accessed from eBird to sell anything (birding tours, books, Aunt Mary's awesome cabin that she rents, etc.). Contacting observers for that reason violates our privacy policy. You may include personal websites, business websites, etc. as part of your email signature or eBird profile, but overt marketing to eBird users is inappropriate.