# Checklist-level review reasons 

Checklist-level review reasons only apply to marking a checklist Not Public; marking a checklist as Public does not require a reason and is an indication that the checklist has been reviewed and the location, date, effort, and other metrics are OK. The most common review reasons below are underlined and preceded by an asterisk (\*). Reasons listed at the end and marked with a dagger (†) are applied by [automated review processes](The_eBird_Checklist_Page.qmd#automatic-checklist-level-reviews) and cannot be used by eBird reviewers.  

**Checklist-Captive Species:** Captive species are never appropriate for eBird; Use this when a checklist includes multiple captive species on a single list or if the majority of the list consists of captive species. If a single captive species is included in a long list of wild species, then it may be better to address that with a review of that species record, but if the observer is clearly not understanding eBird’s prohibition on the entry of captive species, then this checklist flag should be used. 

**Checklist-Date Imprecise:** Use this when an observer submits records from a correct location, but uses a date that is clearly incorrect. Some users submit lists spanning multiple days. eBird does not accept multi-day lists and it is best to make these checklists Not Public using this reason, even if they are otherwise correct. Obvious list-building efforts should be invalidated as Checklist-List Building and incorrectly plotted locations should be made Not Public using one of the Location review reasons below. 

**\*Checklist-Distance Too Long:** Mainland checklists of 80.5 km (50.0 miles) or longer, or High Seas checklists (<https://ebird.org/region/XX>) of 160.9 km (100.0 miles) or longer, are automatically tagged as Checklist-Distance Too Long. Reviewers can override this in rare cases, and if observers correct a typo (e.g., change 50 miles to 5.0 miles) then the checklist can be marked Public by a reviewer; editing the distance does not reverse the automatic tagging.  

One goal of review is to ensure that correctly identified records are plotted reasonably accurately, so that display on a map will not misrepresent the species' range. In general, we believe that most checklists of 8 km (5 miles) or less should be accepted by reviewers and most checklists of 25 km (15 miles) or more should probably be marked Checklist-Distance Too Long, especially if they span multiple habitats. Reviewers must use their best judgment in all cases to not be overly restrictive, but to also steer observers towards shorter and more precise lists. 

**Checklist-Duplicate:** Identical duplicate submissions (from the same observer’s account) should be made Not Public with this reason. Observers sometimes cause this by hitting submit twice rapidly. Often the observer may not know about this, so an email may be appreciated. This SHOULD NOT be used for duplicate lists from different observers, since these are “checklist shares” and are dealt with properly (as a single checklist) in the eBird database. Please note also that this is most important for effort-based complete checklists; some checklists that use Incidental or Historical protocol and report from the same location should not considered duplicates if different media assets or different notes are associated with the records (e.g., certain checklists uploaded from the Internet Bird Collection (IBC) in Feb 2020). 

Some observers share with group accounts (e.g., “Lake County Bird Club” or “September Shorebird Survey”) to aggregate data for an organization or project; this is acceptable and these also should NOT be considered duplicate submissions. Furthermore, some observers may maintain a duplicate account for aggregating specific lists (such as “no playback” or “no heard birds” or “green birding” where they share their own lists). Observers maintaining such accounts should do so using the checklist sharing feature. However, these “group accounts” do need to set their preferences to not appear in the Top 100. In the future, we hope to develop a better way for observers to maintain such lists, but in the meantime this is acceptable and not a reason for invalidation as a duplicate list. 

**Checklist-Error:** This reason is to be used for miscellaneous issues with the checklist that are not covered by the other review reasons (one example would be a checklist reporting entirely captive birds from a zoo). This reason should almost always be accompanied by review notes explaining why the checklist was considered Not Public.  

**\*Checklist-List Building:** It is common for observers to create a life list or a state list by plotting a location or selecting a random point, picking a random date, and submitting a full list of what they've seen over the course of a lifetime or a trip to a given country or state. These do not represent serious attempts to submit data worthy of a scientific database, so these should be made Not Public. Records from these often are easily caught by our filters, and anytime these are identified the entire list should be marked Not Public with this reason. Note that we do formally recommend that users submit such lists using the date of 1 Jan 1900, incidental protocol with no start time (see the [Enter your pre-eBird life list](https://support.ebird.org/support/solutions/articles/48000804866) article) and records from this date are automatically tagged as Checklist-List Building and marked Not Public. If you encounter users entering different dates for such lists, please steer them to this article. 

**Checklist-Multi-party:** eBird is a system for collecting single-party checklists. If two or more observers go birding independently, these birding efforts should be submitted separately. If they are not, it is appropriate to make the list Not Public using this reason if the observer is unwilling to correct his or her list. Christmas Bird Count “sector” data is sometimes submitted this way as an aggregation from multiple independent parties, and this is the appropriate way to address those checklists. 

**Checklist-Protocol Error:** This reason is to be used when eBirders use [protocols](https://support.ebird.org/support/solutions/articles/48000950859) incorrectly. These could include custom protocols, like atlases or specialized surveys, or misuse of Traveling Count or Stationary count protocols. Also, Nocturnal flight call counts should use the special protocol since this makes assumptions about counts and detectability that do not affect eBird output. Please ask observers to change their Nocturnal Flight Call count submissions to this protocol; if they do not, marking them Not Public using this reason may be appropriate. Changing protocol does not automatically remove this tag, so this requires a reviewer. 

**\*Location-Issue:** This review reason is to be used for any case where the observer has badly misplotted the location or has selected the incorrect location. Ideally, the reviewer would email the observer in such cases to inform him or her about the error. Note that use of country, state/province, or county-level locations (from “Submit for an entire country, state, county, or city”) will automatically treat checklists as Not Public using the appropriate review reason. For any Location review reason—including both reviewer-tagged checklists and automatically-tagged checklists—a correction of the location by the user (either a location move or selection of a different location) will remove this checklist-level flag. We assume in such cases that the observer has made the appropriate correction and if not, these will need to be located again; we do not give reviewer notification in such cases. 

†**Location-County Level:** We automatically tag all submissions that come in at the county level (via the “Submit for an entire country, state, county, or city” option) as Unconfirmed, Location-County Level. In other words, reviewers will not find these records unless you search for them. For eBird, submissions at broad levels like county, state, and country have relatively little value, and do not meet our minimum requirements for location specificity and should not appear on the point maps. If you find a record in your review queue that clearly represents a county-level submission (users can still plot a point anywhere and call it “Kern County, California”), please mark it Not Public using Location-Issue. Of course, if a rarity is reported, you may want to follow up to find out if it was correct and, if so, encourage the user to plot it precisely. For all location-based errors, we encourage you to try to educate our users about how to plot records more precisely and make their data more useful. Note also that, as with Location-Issue, when an observer revises the location to a specific location it will remove the Not Public flag. 

†**Location-Country Level:** We automatically tag all submissions that come in at the country level (via the “Submit for an entire country, state, county, or city” option) as Unconfirmed, Location-Country Level. In other words, reviewers will not find these records unless you search for them. See Location-County Level above for more information (the same rules apply, and Country level records are obviously even less precise than County level submissions).  

†**Location-State Level:** We automatically tag all submissions that come in at the state or provincial level (via the “Submit for an entire city, county, state, or country” option) as Unconfirmed, Location-State Level. In other words, reviewers will not find these records unless you search for them. See Location-County Level above for more information (the same rules apply, and State level records are obviously even less precise than County level submissions). 

†**Observer-Suppressed:** Used with Unconfirmed. You do not have an option to set this yourself, but this is the [eBird Blocklist](eBird_Blocklist.qmd) (which also we refer to as Personal-only). Occasional incorrigible observers cause eBird more harm than good, either through unwillingness to engage in the review process, unwillingness to improve their eBirding habits or lack of interest in improving their birding skills, or other problems they cause. We can set specific users to have their data automatically marked as Unconfirmed, but we only do this in extreme cases where there is a clear paper trail to document why we are taking this action. Please request it rarely and only with good reason (e.g., intentional falsification of documentation)! 

†**User Hidden:** This cannot be set by reviewers, but it may appear in the History of a record. This is set when a user selects "Hide this checklist from eBird output" which makes the checklist Not Public and this action cannot be reversed by a reviewer, only by the user (see below).  

†**User Unhidden:** This cannot be set by reviewers, but it may appear in the History of a record. This is set when a user selects "Show this checklist from eBird output" for a checklist that had been previously hidden. This selection makes the checklist Public and this action cannot be set by a reviewer, only by the user (see above).