# eBird Blocklist 

In extreme instances, some eBird users are not a good fit for eBird. This can be because the individual reports rare birds at a rate that strains credulity, because he/she refuses to engage with the review process, or because he/she has shown a pattern of rude or abusive behavior. When an individual begins to cause eBird and the review community more harm than good, we almost always send a warning letter informing the individual of potential account suspension. If the behavior persists, the individual may be blocklisted. This process automatically marks these checklists Not Public upon submission with reason Observer-Suppressed and removes their records from all output. The observer also does not appear in Top100 and his/her records do not appear on Alerts. This can be reversed only by eBird Central and would only apply to future records, not past checklists already marked Not Public. These records may appear in search and could be reversed if reviewed by a reviewer, but we do not recommend this. Note that checklists shared from an account on the blocklist will also be treated as Not Public (since review Histories) are shared; if two friends bird together and share checklists between them, it is important to have the account that is Public keep the checklists and share with the other person. 

Intentional falsification does occur; our Additional Documentssection refers to our document **Falsification of documentation and how to detect it** (email your contact at eBird Central (e.g., Marshall) to request this document). eBird has a zero-tolerance policy on the intentional falsification of documentation. Every case needs to be dealt with on an individual basis, and some cases (e.g., young children) may be worth rehabilitating. Officially, a single proven instance of falsification of documentation is justifiable grounds for blocklisting. If you request such a case, please do provide documentation that proves the falsification. 

Note that the eBird Blocklist is not intended for novice/beginner birders, especially young birders. We believe that eBird can be used and enjoyed by birders of all skill levels; honest mistakes are best addressed with the existing review process. Observers usually learn quickly, especially when given constructive feedback. We try to avoid blocklisting whenever possible. When we do blocklist users, we consistently try to ensure that they have been made aware of the problems and have been given a chance to resolve them; we also ensure that reasons for blocklisting are well documented. If you have a problem observer in your region and would like to consider submitting a blocklist request, please use [eBird Blocklisting Form](https://docs.google.com/forms/d/e/1FAIpQLSc33hOHbYLBrQkqPDvm1PpVz-ksI3yzECAHNKABQTb8Iss4Eg/viewform?usp=send_form) which will guide you through the process and help clarify what eBird Central needs to move forward.

**Trespassing and other illegal activity**

eBird reviewers are not the police, and we expect reviewers to review records based on their merits and leave legal issues to law enforcement. If a bird was found illegally or unethically, that should have no bearing on its scientific validity. If a rare species of interest to birders is present in an area that is not open to the public, it is OK to leave that record unreviewed or to temporarily treat it as Unconfirmed using the reason Species-Sensitive Species until the bird no longer presents a temptation to would-be chasers.