# Introduction 

Thank you for your willingness to assist with reviewing eBird records. eBird reviewers like you are selected not only for your knowledge and skill with bird identification and understanding of bird distribution patterns, but also for your interpersonal skills and connections to the birding community. As an eBird reviewer, we hope you not only use eBird regularly but will set an example for best eBirding practices and will provide mentorship in your correspondence with eBirders. We strongly recommend that all eBird editors take the free, brief [eBird Essentials Course](https://academy.allaboutbirds.org/product/ebird-essentials/) and understand how to communicate the basic concepts discussed in the course. 

You will interact with eBirders of all skill levels, from rank amateurs to professional ornithologists. Humility and tact are essential in your correspondences, and we hope that the focus is on finding the truth and ensuring exceptional records are exceptionally well-documented. We also hope you’ll recognize that birds are dependent on inviting as many people as possible into our wonderful field, and that you’ll have patience in your interactions with people who have just started learning their local birds, for example, with Merlin Sound ID. 

You will represent the eBird project as one of the primary points of contact for our user community. Please do what you can to encourage users in a supportive manner and help build the eBird community. People make mistakes. We encourage you to contact and assist them. If you continually treat records as Unconfirmed without letting people know, they are unlikely to learn, will keep making the same mistakes, and this will ultimately take more time. 

Data quality is of paramount importance at eBird. Many of us currently are on records committees or have been in the past, and we take documenting rarities very seriously. It is an ongoing challenge to identify and assess data coming into eBird. We will continue to develop new ways of exploring the data that will help to bring potentially erroneous records to light, but we depend on you to discover and assess these records in your region. 

There are three main components to this document, Part I covers using the review tools, Part II covers filter creation and editing, and Part III covers important policies and guidelines. 

**NOTE: This document is the November 2025 version and is always available at this link in the eBird Help Center: <https://tinyurl.com/eBirdReview>. Please use this link to access the latest version of this document.** 

Most importantly, thank you for your help in building eBird and making it better. Without you, eBird would not exist. If there is anything we can do to help, please contact us at any time.  

Thank you, 

Marshall Iliff: mji26\@cornell.edu 

Jenna Curtis: jenna.curtis\@cornell.edu  

John Garrett: jfg228\@cornell.edu