## Non-species Taxa on eBird Filters 

The use of non-species taxa (subspecies, slashes, spuhs, hybrids, intergrades, domestics, forms, etc.) on eBird filters is one of the more complex aspects of filter creation and maintenance. We have formal recommendations for inclusion of non-species taxa on eBird filters in the United States and Canada (see [that document here](https://docs.google.com/document/d/1qRo-welPf8LrxpObXrS4QXszTm2m4zN0LzdZYlMkMNI/edit?tab=t.0#heading=h.eif8wvwb6f60)), but the general philosophy applies globally, and these examples should guide filter standards elsewhere in the world. 

For the U.S. and Canada, there is a companion spreadsheet (**Filter taxa recommendations_USA and Canada.xlsx**) that gives formal recommendations for all potential non-species taxa north of Mexico. This spreadsheet categorizes all eBird non-species taxa in the three categories described below in the ISSF (subspecies group) example. In addition to providing recommendations for all non-species taxa this document also provides specific recommendations for all introduced species. US and Canada editors should refer to this document and strive to make your filters consistent with these recommendations. 

This file is available here: <https://tinyurl.com/eBirdReview>