# Novice eBirders and Merlin Sound ID  

Please note that eBird is open and welcoming to new birders, including those who are just beginning to learn how to identify birds using Merlin Sound ID. We encourage birders to use eBird even while they are still learning (who isn’t?) and there is demonstrable evidence that using eBird helps new birders grow their skills.

Our hope is that these birders will report cautiously, acknowledge uncertainty when it exists, and interact positively with the review process. Whenever an eBirder is encountered who does not understand basic elements of eBird reporting—plotting precise locations, understanding of complete checklists, etc.—please steer them to the free [eBird Essentials Course](https://academy.allaboutbirds.org/product/ebird-essentials/). We hope to continue to develop better support for this community in the coming years, including more training and more opportunities to track personal observations in eBird but to not have those used for public data. Please be patient with new users and please share your knowledge when you can—this is how we all learn. 

The Great Backyard Bird Count, which occurs annually on Friday-Monday across the third weekend in February, is a global count effort that tends to engage lots of novice users. Most of these new users submit via the GBBC portal (<https://gbbc.birdcount.org/>); remember that these records can be removed from your Review Queue using the Filter option and selecting Hide Records from and Great Backyard Bird Count. This can be helpful in regions with high GBBC participation where you want to ignore these records or save them for later. However, for the most part the impact of the GBBC is minimal and the records are but a small subset of the total in eBird.