## Part 1: How to use the Review Tools

1.  [Important Terms to Know](Important_Terms_to_Know.qmd)
2.  [Accessing the Review Tools](Accessing_the_Review_Tools.qmd)
3.  [Your Review Assignment](Your_Review_Assignment.qmd)
4.  [Navigating the Review Tools](Navigating_the_Review_Tools.qmd)
5.  [What Records Appear in the Review Queue](What_Records_Appear_in_the_Review_Queue.qmd)
6.  [Review Decision, Status, and Reason](Review_Decision_Status_and_Reason.qmd)
7.  [Sequence of the eBird Review Process](Sequence_of_the_eBird_Review_Process.qmd)
8.  [How to Review Observations](How_to_Review_Observations.qmd)
9.  [The eBird Observation Page](The_eBird_Observation_Page.qmd)
10. [The eBird Checklist Page](The_eBird_Checklist_Page.qmd)
11. [Quick Review](Quick_Review.qmd)
12. [Review Decisions and Reason Email Templates](Review_Decisions_and_Reason_Email_Templates.qmd)
13. [Reviewing Shared Checklists](Reviewing_Shared_Checklists.qmd)
14. [Exotic Species](Exotic_Species.qmd)
15. [Other Reviewing Options](Other_Reviewing_Options.qmd)
16. [Common Source Errors](Common_Source_Errors.qmd)
17. [Search Observations](Search_Observations.qmd)
18. [Using eBird's Explore Data Tools to Find Records for Review](Using_eBirds_Explore_Data_Tools_to_Find_Records_for_Review.qmd)
19. [Sensitive Species](Sensitive_Species.qmd)