## Records Committees 

eBird supports the work of regional Bird Records Committees (BRCs). Our process for archiving photos, videos, and audio into posterity should be a great service to any Records Committee. eBird’s review processes should be complementary and collaborative with BRCs where possible. We ask that eBird reviewers: 

-   Share interesting records with BRCs 

<!-- -->

-   Facilitate and, where appropriate, share information on correspondence with the observer 

<!-- -->

-   Defer to the BRC decision in almost all cases, unless there is good reason to do otherwise. This is especially true for controversial records, such as those documented by written description only. 

However, it is also of paramount importance that eBird reviewers: 

-   Review records in a timely manner 

<!-- -->

-   Not delay decisions until BRC review is complete and published 

Thus, we recommend that eBird Reviewers make preliminary decisions on records under review by Bird Records Committees. At the time of publication of BRC decisions, eBird reviewer decisions can be rechecked and revised, if needed. Ideally the BRC would assist with this process. Resolving areas of discrepancy can occur when they are discovered or reported.  

Therefore, if a well-documented Ross’s Gull appears in your area and is well-photographed and seen by hundreds, please don’t delay for the BRC decision. Likewise, if a Brown-chested Martin is reported and you believe the photos show a Purple Martin, please don’t delay in making that assessment. If you strongly believe a committee has erred in the treatment of a record, we encourage you to promote the re-review of the record by the committee. Write a statement defending how you would treat the record and submit it for consideration by the committee. And if you depart from a committee decision with your eBird review (which we generally do not recommend), please be sure to provide extensive commentary within the record to defend your departure from their decision. 

In many cases, a Records Committee should need nothing more than a checklist link in order to review a report with location, date, observer name, description, and photos. Encourage your local Records Committee to archive eBird Checklists by printing them or saving them as a PDF. Bird Records Committees interested in collaborating more closely with eBird can get in touch with eBird Central (i.e., Marshall) for a document that outlines approaches to streamline record review and collaborate with eBird. This approach has been used in the USA in Massachusetts for many years now and greatly streamlines the process; other states have been increasingly adopting it as well. 

Note that BRC decisions on exotic species are addressed in the following section; those decisions should be followed and should define species treated as Naturalized. eBird also has a Provisional category, which is shared by some but not all BRCs; obviously eBird editors will need to judge these for themselves in cases where the BRC does not assess records in this way.