# Review Decisions and Reason email templates 

The review reasons available in Quick Review and by clicking on an email icon next to a record in the queue are a streamlined list relevant for records with documentation. Please see [Appendix A](Review_Reasons.qmd) for a full description of review reasons.  

Each review reason includes a custom email template and all have an option to a custom text block to provide the observer with more information. We recommend reading these emails before sending; opening the email will display it, but it won’t be sent until you hit Send. **We strongly recommend adding a short note in the box provided to personalize your emails**. Setting these off with boldface and italics helps make sure the observer does not miss this text. 

You always have the option to send or not send the email, but this must be designated when the first box pops up and allows you to set your reason; just check or uncheck the Send Email box. If you choose to send an email, the review actions will be finalized when the email is sent. Note that Shared checklists will have all participants on the checklist CCed by default; you can uncheck those whom you don’t wish to email. 

**Email templates for Accept**

-   **Accept:** Checking Send email will also send a thank you note to the observer. Please use this for any particularly well-documented record or just to say thanks to anyone or mention something interesting about a record you are accepting. This injects some great positivity into the process! 

**Email templates for Unconfirm and Defer**

-   **Documentation Inadequate-Count:** This email asks the observer for more documentation on a high count and explains why it is important, and links to[ our article on counting birds](https://support.ebird.org/en/support/solutions/articles/48000838845-how-to-count-birds). 

<!-- -->

-   **Documentation Inadequate-Species:** This email asks the observer for more documentation on a rare record, explains why it is important, and links to our article on documenting rare birds.  

<!-- -->

-   **Media-ID questioned:** This email is specifically for records that include correctly identified media mixed with incorrectly identified media. This could be a drag-and-drop error or misidentification. The email explains to fix this using [Change Species](Other_Reviewing_Options.qmd#change-species). NOTE: This email will appear unfinished if you do not add text in the target box. 

<!-- -->

-   **Merlin ID-Documentation Inadequate:** This template is the same as Documentation Inadequate-Species, but tailored specifically to circumstances when you know or strongly suspect the user was uncritically accepting an ID generated by the Merlin app. It encourages the recipient to identify the bird for themselves. 

<!-- -->

-   **Merlin ID-Species Misidentified:** This template is the same as Species-Misidentified but tailored specifically to circumstances when you know or strongly suspect the user was uncritically accepting an ID generated by the Merlin app. It encourages the recipient to identify the bird for themselves. 

<!-- -->

-   **Species-Misidentified:** This email explains that a species has been misidentified and gives instructions for how to make the correction using [Change Species](Other_Reviewing_Options.qmd#change-species). NOTE: This email will appear unfinished if you do not add text in the target box, hopefully including the correct species and some additional helpful ID notes. 

<!-- -->

-   **Species-Taxonomic Issue:** This email explains that the issue with the record is more from confusion over the selected name or recent taxonomic revision and suggests how to make this change. Please read more about this reason in Appendix A and understand how to use it correctly. NOTE: This email will appear unfinished if you do not add text in the target box, hopefully explaining the issue briefly. 

As with all records with a Deferred status, if you want to keep records in your queue indefinitely, immediately mark Unconfirmed with a reason of Species-Rereview Requested. 

Several other reasons in Quick Review (BRC-Rejected, Observer-Error) are rarely used and have a generic template under Unconfirm that is similar to the one used in traditional review but without a request for more documentation. These email templates need you to fill in some information about the problem, if you use them.