# Review Teams 

In many regions we have more than one reviewer and we hope that a review team develops open channels of communication and agreement on how to share the workload and divide review responsibilities. It is obviously ideal not to contact eBirders multiple times about a given record, so paying attention to who has already been in touch about records (i.e., those marked Deferred) is important. Use the Observation Page History to keep track of emails to observers and other actions by reviewers. In some cases, you may want to enter into the notes box something like “Reviewer X is contacting the observer” so that other reviewers in your state don’t pursue it.  

## Adding or removing reviewers 

We are always willing to add new reviewers for a region. If you have a suggestion of someone to add, please introduce us to the person and provide a link to their profile or one of their checklists in eBird. Please let us know also if you or another reviewer should be removed (and why). Reviewers can only be added or removed by eBird staff, including regional coordinators for some eBird portals. 

## List of active reviewers 

A list of our current reviewers is in Google Docs: <http://bit.ly/1CFRUlX>. You can view the current editors and their assignment but will be unable to edit this document. Feel free to get in touch with other editors. Please let us know of changes; we update this list about once a month. 

## eBird Mentors 

In some regions, one reviewer will take on the role to help novice birders with their reports. This can include being the point person to follow up with observers about misidentified photos, assisting observers who struggle to provide accurate locations or to follow eBird [protocols](https://support.ebird.org/support/solutions/articles/48000950859), or working in a compassionate manner with new birders or new eBirders who are trying to contribute positively to the project. **We strongly endorse review teams that include someone with this focus.** If you do not have an eBird tutor on your team, or if you are not regularly helping newer users yourself, please get in touch and consider adding a passionate eBirder who might be willing to fill this role and help eBird users in your region.