# Special Scenarios 

## Captive species or zoo reports 

Reports of captive birds from zoos, wildlife parks, or waterfowl collections are **not appropriate for eBird**, which is intended to collect information on free-flying birds. If multiple captive species are included on one list, please review at the checklist-level and use the Checklist-Captive Species review reason. These records can also be marked Exotic-Escapee, which will prevent these records from appearing on personal list totals and will help to stress the problems with this type of reporting to the observer. Please note that this extra step may be required in addition to marking the checklist Not Public. 

Sometimes, however, the fact that a bird is a captive is not obvious to the eBirder. Some species live in a semi-wild state that return nightly to yards, barns, or lodges (e.g., certain semi-captive trumpeters at South American lodges or American Flamingos at Caribbean resorts). Mute Swans (often pinioned) are sometimes temporarily released on lakes during the summer and then recaptured for winter. As with birds in zoos, these birds represent captive individuals, should be invalidated using the reason Observer-Error and reviewers should include comments that these are captive birds or that the checklist includes caged birds from a zoo. It is very important that you contact the eBirder to ask that the captive species be removed from their list and implore them not to report captive birds in the future (it is OK for the observer to add mention of these birds in Checklist Comments).  

We recognize that determining whether an observation represents a free-roaming captive bird or free-flying Escapee can be difficult to determine at times. We ask that reviewers make their best guess and when an individual may be captive to treat it as such. Mute Swans and certain other waterfowl, along with Domestic types of Red Junglefowl, Helmeted Guineafowl, Indian Peafowl and Wild Turkeys are the most common instances of captive birds that roam freely. 

## Wild birds in buildings 

Occasionally wild birds end up inside buildings where they may spend the winter. These records should be accepted unless there is strong evidence that the bird did not arrive there on its own. For example, a hummingbird captured (this is usually illegal) and moved inside a greenhouse by a person should be Unconfirmed with reason Observer-Error, since the bird essentially becomes a captive (as with zoo birds). If, however, the hummingbird appeared inside the greenhouse on its own, the bird can be Accepted. 

## Remotely-sensed birds 

Reporting remotely-sensed birds in eBird is permitted but not encouraged (we explicitly[ discourage it in eBird’s Help Center](https://support.ebird.org/en/support/solutions/articles/48000795623-ebird-rules-and-best-practices#Why-doesn't-eBird-accept-observations-of-dead,-captive,-or-remotely-sensed-birds?)), but we also know that these checklists will continue to come in. Checklists built from watching webcams or identifying birds from other remote-sensing projects birds can be Public in eBird, but the eBirder must abide by the below guidelines. Records of remotely-sensed birds can be Accepted if they are sufficiently documented. Since remote sensing involves capturing and archiving imagery and/or audio, review is usually straightforward. Remotely-sensed checklists must adhere to these guidelines: 

1.  Report on a checklist using Incidental protocol and “No” to all species reported because remote sensing cannot match the detection abilities of an observer in the field. 

<!-- -->

2.  Report from a dedicated account for these efforts (opted out of Top100) because remotely-sensed records must not be used to “pad” one’s Top100 standing. 

<!-- -->

3.  Report from the approved hotspot, if it exists 

4.  Documentation should only be included with permission of the project, since the imagery/audio may be copyrighted. Providing a link to the project website is acceptable or alternatively the project may manage its own account and upload the imagery. 

## Dead birds 

eBirders occasionally report dead birds (or only feathers) on their eBird checklists, sometimes including photos. eBird is not intended for recording dead birds and in most cases dead birds should not be reported. Inclusion of dead birds on complete checklist introduces biases inconsistent with eBird’s focus on surveys of live birds by birdwatchers.  

Exceptions can be made for records that are particularly unusual following the rules below. 

1.  Dead birds should only be entered when they represent unusual records. As a general guideline, unusual should be considered as no more than 5 records within the last 5 years for a county or county equivalent. 

<!-- -->

2.  Dead birds should be reported from a specific account that is dedicated to historical records or rare records within a region. This account should be opted out of the Top 100. The person entering the report should state who entered the record, when, and the source. 

<!-- -->

3.  Reports of dead birds should use the Historical or Incidental[ protocol](https://support.ebird.org/support/solutions/articles/48000950859) and a count of at least 1 (not zero). Answer “No” to the question “Are all species being reported?” 

<!-- -->

4.  Birds should be dead no more than about 48 hours and should not show signs of advanced decomposition (maggots, strong odor, dried or deflated eyes). Be particularly cautious of birds washed up on beaches. In cases where this represents a record for which there are fewer than 3 records for a state or country, we can make exceptions to this providing details are clearly included in the comments in the checklist and the other guidelines are followed. 

<!-- -->

5.  Comments should address the condition of the bird. For a detailed guide to estimating time of death in selected wildlife species see[ this document](https://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1063&context=nebgamestaff). 

Examples of appropriate dead bird reports include Maine’s first Trindade Petrel (<https://ebird.org/checklist/S25558221>) or the only US record of Gray Nightjar (<https://ebird.org/checklist/S21527383>). 

In cases where the above standards are not followed, we recommend following up with the observer and clarifying this policy. Dead birds reported on complete checklist should be marked Unconfirmed with reason Observer-Error and a comment reflecting why. **Note:** Currently Macaulay photos can be correctly tagged as “dead” only in the quiz. In the future, we plan to refine this so that photos of dead birds can be correctly tagged whenever found.