# Timeliness 

We consider punctual review to be important and urge you to review your records at least once a week, if not daily. Quick Review makes this particularly easy. If you are unable to review records once-a-week on average, please consider adding a person to your review team to help out and get in touch with eBird Central to add that person. Records that are not Accepted will be excluded from our bird occurrence summaries if review is not timely. eBird is bringing birding into the information age and several of our tools, and many of those we are currently developing, depend on the ability to get bird information quickly, or even in real time. There are exceptions, such as eBird Alerts that do provide near real-time lists of all records reported to eBird. If the species is flagged, it will be noted as Unconfirmed on Alerts. If you review it and treat it as Unconfirmed, it will be removed from all eBird output. If the record is Deferred, it will remain on the Alerts (which include records up to 7 days old); this can be a useful way to keep interesting records in view so that others can try to document them. 

We also understand that real life may occasionally get in the way and the world (even the bird world) will not stop spinning on its axis if your review list backs up a bit. We expect eBird users to understand this and be patient with review of their records. If you work as a team, please consider having other reviewers cover you while you are away. If not, don't stress about it! It may be worth alerting the local birding community that eBird reviews will be on hold until you get back. Please suggest other people who could help with the review process if needed.