# Using eBird’s Explore Data Tools to Find Records for Review 

eBird’s Explore pages provide rich resources to identify interesting outlier records. The Review Tools have limitations. For instance, it is not easy to find all inland records of Common Eiders in New England, USA, for large counties that touch the coast. This can be easily addressed using eBird Range Maps, which are another entry point for review. 

**Point Maps:** Using [Species Maps](https://ebird.org/map) to map individual observations can identify geographical outliers, or records that seem out of place. For example, coastal birds plotted inland or terrestrial species plotted offshore. There are also similar-looking species that overlap in their distributions, providing challenges to the casual observer but not flagged by filters. For example, where ranges overlap for Black-capped and Carolina chickadees in the eastern US, reviewers might have to look at records on the Species Maps to ensure that no points are way out of each species’ typical range. Species Maps may be the only efficient way to correct such errors, since the regional filters may not be able to catch them. Click on points in the Species Map to obtain the checklist link and review directly from there. To find reports outside of the expected date range, use the Date drop-down in the menu bar to limit which points are shown.  

**Bird lists for regions, hotspots, and** . For example: <https://ebird.org/region/USFWS_14/bird-list>. These display when a species was first seen, most recently seen, and its high count for either the current year or all years (default). To review the records just click the date from this page (or almost anywhere in eBird) to get the checklist review page. 

[**Rare Bird Alerts**](https://ebird.org/alerts) for your review region will send email notifications (hourly or daily) with checklist links that you can use for review. Since these reports are being watched by others, quick review is always welcome. This is a very useful way to keep up with incoming records and to be promptly notified of rarities submitted.