# Your review assignment  

Each reviewer is set up with at least one Review Assignment. Assignments usually correspond to a region (e.g., country, state, county) but can also be defined by Arbitrary Polygons (custom filter regions developed at Cornell). These Review Assignments show on your[profile page](https://ebird.org/profile) and in the Review Tools and define what records you have access to in the Review Tools. Reviewers cannot review records from regions not included in their Review Assignments.  

Please note that Review Assignments are particularly useful in Quick Review (see [Quick Review](Quick_Review.qmd)) since other filtering tools are not currently provided (e.g., filters by county, state, or species). If you review for an area larger than one county (or one state/province in areas that don’t have counties in eBird) then it may be useful to have multiple review assignments for the purposes of filtering.  

Get in touch with eBird Central for help setting up new assignments. 

**What if I can’t see any records?**

If you log into the Review Tools and see a message saying “You have no more records to review,” please try logging out of eBird and the Review Tools and then logging in again. If you still aren’t seeing records, try to search for a record of a fairly rare bird that you know has been recorded in your region (see [Search Observations](Search_Observations.qmd) below for information on how to use Search).  

If you still do not see any records, please contact us, as there may have been an error in setting up your Review Assignment.